catalogs:
  build:
    tsdown: ^0.12.9
  cli:
    citty: ^0.1.6
    consola: ^3.4.2
    tmcp: ^1.8.2
  deps:
    defu: ^6.1.4
    leaflet: ^1.9.4
    puppeteer: ^24.15.0
    valibot: ^1.1.0
    vue: ^3.5.18
  dev:
    '@vitejs/plugin-vue': ^6.0.1
    bumpp: ^10.2.0
    changelogen: ^0.6.2
    typescript: ^5.8.3
    vite: ^7.0.6
    vite-plugin-singlefile: ^2.3.0
    vue-tsc: ^3.0.4
  lint:
    '@antfu/eslint-config': ^4.19.0
    eslint: ^9.32.0
    lint-staged: ^16.1.2
    simple-git-hooks: ^2.13.0
  mcp:
    '@tmcp/adapter-valibot': ^0.1.3
    '@tmcp/transport-stdio': ^0.1.2
  types:
    '@types/leaflet': ^1.9.20
    '@types/node': ^24.1.0

onlyBuiltDependencies:
  - esbuild
  - puppeteer
  - simple-git-hooks
